export const envKeys = {
  PG_USER: 'POSTGRES_USER',
  PG_PASSWRD: 'POSTGRES_PASSWORD',
  PG_DB_NAME: 'POSTGRES_DB',
  PG_PORT: 'POSTGRES_PORT',
  NODE_ENV: 'NODE_ENV',
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_TOKEN_TTL: 'JWT_ACCESS_TOKEN_TTL',
};
